// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Yggdrasil.Infrastructure.Persistence;

#nullable disable

namespace Yggdrasil.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260801181149_Mig01")]
    partial class Mig01
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Yggdrasil.Domain.Entities.CAT_Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NomEmpresa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("NomEmpresa")
                        .HasDatabaseName("IX_CAT_Empresas_NomEmpresa");

                    b.ToTable("CAT_Empresas", (string)null);
                });

            modelBuilder.Entity("Yggdrasil.Domain.Entities.CAT_Moneda", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("ClaveMoneda")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("NomMoneda")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("PorDefecto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("ClaveMoneda")
                        .IsUnique()
                        .HasDatabaseName("IX_CAT_Monedas_ClaveMoneda");

                    b.ToTable("CAT_Monedas", (string)null);
                });

            modelBuilder.Entity("Yggdrasil.Domain.Entities.CAT_Periodicidad", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("ClavePeriodicidad")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("NomPeriodicidad")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<short>("NroPagosAnio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0);

                    b.Property<short>("NroPagosMes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0);

                    b.Property<short>("ParamDias")
                        .HasColumnType("smallint");

                    b.Property<short>("ParamMes")
                        .HasColumnType("smallint");

                    b.Property<bool>("UsaDias")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ClavePeriodicidad")
                        .IsUnique()
                        .HasDatabaseName("IX_CAT_Periodicidades_ClavePeriodicidad");

                    b.ToTable("CAT_Periodicidades", (string)null);
                });

            modelBuilder.Entity("Yggdrasil.Domain.Entities.CAT_Plazo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("ValorPlazo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ValorPlazo")
                        .IsUnique()
                        .HasDatabaseName("IX_CAT_Plazos_ValorPlazo");

                    b.ToTable("CAT_Plazos", (string)null);
                });

            modelBuilder.Entity("Yggdrasil.Domain.Entities.CAT_Tasa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("Activo");

                    b.Property<bool>("EsVariable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("EsVariable");

                    b.Property<string>("NomTasa")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar")
                        .HasColumnName("NomTasa");

                    b.Property<decimal>("ValorTasa")
                        .HasColumnType("decimal(8, 4)")
                        .HasColumnName("ValorTasa");

                    b.HasKey("Id");

                    b.HasIndex("Activo")
                        .HasDatabaseName("IX_CAT_Tasa_Activo");

                    b.HasIndex("EsVariable")
                        .HasDatabaseName("IX_CAT_Tasa_EsVariable");

                    b.HasIndex("NomTasa")
                        .IsUnique()
                        .HasDatabaseName("IX_CAT_Tasa_NomTasa_Unique");

                    b.HasIndex("Activo", "EsVariable")
                        .HasDatabaseName("IX_CAT_Tasa_Activo_EsVariable");

                    b.ToTable("CAT_Tasa", (string)null);
                });

            modelBuilder.Entity("Yggdrasil.Domain.Entities.CAT_TasaIva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("NomTasaIva")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<decimal>("ValorTasa")
                        .HasColumnType("decimal(8,4)");

                    b.HasKey("Id");

                    b.HasIndex("NomTasaIva")
                        .HasDatabaseName("IX_CAT_TasasIva_NomTasaIva");

                    b.ToTable("CAT_TasasIva", (string)null);
                });

            modelBuilder.Entity("Yggdrasil.Domain.Entities.CAT_TasaValor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("datetime")
                        .HasColumnName("Fecha");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("FechaRegistro")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("TasaId")
                        .HasColumnType("int")
                        .HasColumnName("TasaId");

                    b.Property<decimal>("ValorTasa")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("ValorTasa");

                    b.HasKey("Id");

                    b.HasIndex("Fecha")
                        .HasDatabaseName("IX_CAT_TasaValor_Fecha");

                    b.HasIndex("TasaId")
                        .HasDatabaseName("IX_CAT_TasaValor_TasaId");

                    b.HasIndex("TasaId", "Fecha")
                        .IsUnique()
                        .HasDatabaseName("UK_CAT_TasaValor_TasaId_Fecha")
                        .HasFilter("[Fecha] IS NOT NULL");

                    b.ToTable("CAT_TasaValor", (string)null);
                });

            modelBuilder.Entity("Yggdrasil.Domain.Entities.SYS_AccessPoint", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccessPointName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AccessPointTypeId")
                        .HasColumnType("int");

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<string>("DescPageElement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsAnonymous")
                        .HasColumnType("bit");

                    b.Property<int>("MenuId")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("PageElementId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PluginId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AccessPointTypeId")
                        .HasDatabaseName("IX_SYS_AccessPoints_AccessPointTypeId");

                    b.HasIndex("ApplicationId")
                        .HasDatabaseName("IX_SYS_AccessPoints_ApplicationId");

                    b.HasIndex("MenuId")
                        .HasDatabaseName("IX_SYS_AccessPoints_MenuId");

                    b.HasIndex("PluginId")
                        .HasDatabaseName("IX_SYS_AccessPoints_PluginId");

                    b.ToTable("SYS_AccessPoints", (string)null);
                });

            modelBuilder.Entity("Yggdrasil.Domain.Entities.SYS_AccessPointType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("AccessPointTypeName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("AccessPointTypeName")
                        .IsUnique()
                        .HasDatabaseName("IX_SYS_AccessPointTypes_AccessPointTypeName");

                    b.ToTable("SYS_AccessPointTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 0,
                            AccessPointTypeName = "LeftMenu"
                        },
                        new
                        {
                            Id = 1,
                            AccessPointTypeName = "Page"
                        },
                        new
                        {
                            Id = 2,
                            AccessPointTypeName = "Element"
                        });
                });

            modelBuilder.Entity("Yggdrasil.Domain.Entities.SYS_Application", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("ApplicationName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationName")
                        .IsUnique()
                        .HasDatabaseName("IX_SYS_Applications_ApplicationName");

                    b.ToTable("SYS_Applications", (string)null);
                });

            modelBuilder.Entity("Yggdrasil.Domain.Entities.SYS_Audit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AuditEventId")
                        .HasColumnType("int");

                    b.Property<bool>("HasError")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegisteredDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("AuditEventId")
                        .HasDatabaseName("IX_SYS_Audits_AuditEventId");

                    b.HasIndex("RegisteredDate")
                        .HasDatabaseName("IX_SYS_Audits_RegisteredDate");

                    b.HasIndex("UserName")
                        .HasDatabaseName("IX_SYS_Audits_UserName");

                    b.ToTable("SYS_Audits", (string)null);
                });

            modelBuilder.Entity("Yggdrasil.Domain.Entities.SYS_AuditEvent", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Description")
                        .IsUnique()
                        .HasDatabaseName("IX_SYS_AuditEvents_Description");

                    b.ToTable("SYS_AuditEvents", (string)null);
                });

            modelBuilder.Entity("Yggdrasil.Domain.Entities.SYS_Consecutivo", b =>
                {
                    b.Property<string>("NombreTabla")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ConsecutivoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FecUltimoCambio")
                        .HasColumnType("datetime2");

                    b.HasKey("NombreTabla");

                    b.ToTable("SYS_Consecutivo");
                });

            modelBuilder.Entity("Yggdrasil.Domain.Entities.SYS_LoginLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Agent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ip")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSuccessd")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.ToTable("SYS_LoginLog");
                });

            modelBuilder.Entity("Yggdrasil.Domain.Entities.SYS_Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Icon")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_SYS_Menus_Name");

                    b.ToTable("SYS_Menus", (string)null);
                });

            modelBuilder.Entity("Yggdrasil.Domain.Entities.SYS_Plugin", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<bool>("MenuGlobal")
                        .HasColumnType("bit");

                    b.Property<string>("PluginDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("PluginName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId")
                        .HasDatabaseName("IX_SYS_Plugins_ApplicationId");

                    b.HasIndex("PluginName")
                        .HasDatabaseName("IX_SYS_Plugins_PluginName");

                    b.ToTable("SYS_Plugins", (string)null);
                });

            modelBuilder.Entity("Yggdrasil.Domain.Entities.SYS_Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Yggdrasil.Domain.Entities.SYS_RolAccessPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("AccessPointId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccessPointId")
                        .HasDatabaseName("IX_SYS_RolAccessPoints_AccessPointId");

                    b.HasIndex("RolId", "AccessPointId")
                        .IsUnique()
                        .HasDatabaseName("IX_SYS_RolAccessPoints_RolId_AccessPointId");

                    b.ToTable("SYS_RolAccessPoints", (string)null);
                });

            modelBuilder.Entity("Yggdrasil.Domain.Entities.SYS_Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSpecial")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NombreCompleto")
                        .HasDatabaseName("IX_AspNetUsers_NombreCompleto");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Yggdrasil.Domain.Entities.SYS_Rol", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Yggdrasil.Domain.Entities.SYS_Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Yggdrasil.Domain.Entities.SYS_Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Yggdrasil.Domain.Entities.SYS_Rol", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Yggdrasil.Domain.Entities.SYS_Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Yggdrasil.Domain.Entities.SYS_Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Yggdrasil.Domain.Entities.CAT_TasaValor", b =>
                {
                    b.HasOne("Yggdrasil.Domain.Entities.CAT_Tasa", "CAT_Tasa")
                        .WithMany("CAT_TasaValor")
                        .HasForeignKey("TasaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CAT_Tasa");
                });

            modelBuilder.Entity("Yggdrasil.Domain.Entities.SYS_AccessPoint", b =>
                {
                    b.HasOne("Yggdrasil.Domain.Entities.SYS_AccessPointType", "SYS_AccessPointType")
                        .WithMany()
                        .HasForeignKey("AccessPointTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Yggdrasil.Domain.Entities.SYS_Menu", "SYS_Menu")
                        .WithMany("SYS_AccessPoint")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Yggdrasil.Domain.Entities.SYS_Plugin", "SYS_Plugin")
                        .WithMany("SYS_AccessPoint")
                        .HasForeignKey("PluginId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SYS_AccessPointType");

                    b.Navigation("SYS_Menu");

                    b.Navigation("SYS_Plugin");
                });

            modelBuilder.Entity("Yggdrasil.Domain.Entities.SYS_Audit", b =>
                {
                    b.HasOne("Yggdrasil.Domain.Entities.SYS_AuditEvent", "SYS_AuditEvent")
                        .WithMany()
                        .HasForeignKey("AuditEventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SYS_AuditEvent");
                });

            modelBuilder.Entity("Yggdrasil.Domain.Entities.SYS_Plugin", b =>
                {
                    b.HasOne("Yggdrasil.Domain.Entities.SYS_Application", "SYS_Application")
                        .WithMany()
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SYS_Application");
                });

            modelBuilder.Entity("Yggdrasil.Domain.Entities.SYS_RolAccessPoint", b =>
                {
                    b.HasOne("Yggdrasil.Domain.Entities.SYS_AccessPoint", "SYS_AccessPoint")
                        .WithMany("SYS_RolAccessPoint")
                        .HasForeignKey("AccessPointId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Yggdrasil.Domain.Entities.SYS_Rol", "SYS_Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SYS_AccessPoint");

                    b.Navigation("SYS_Rol");
                });

            modelBuilder.Entity("Yggdrasil.Domain.Entities.CAT_Tasa", b =>
                {
                    b.Navigation("CAT_TasaValor");
                });

            modelBuilder.Entity("Yggdrasil.Domain.Entities.SYS_AccessPoint", b =>
                {
                    b.Navigation("SYS_RolAccessPoint");
                });

            modelBuilder.Entity("Yggdrasil.Domain.Entities.SYS_Menu", b =>
                {
                    b.Navigation("SYS_AccessPoint");
                });

            modelBuilder.Entity("Yggdrasil.Domain.Entities.SYS_Plugin", b =>
                {
                    b.Navigation("SYS_AccessPoint");
                });
#pragma warning restore 612, 618
        }
    }
}
