<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>


  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Ardalis.Result" Version="10.1.0" />
    <PackageReference Include="BitzArt.Blazor.Cookies.Client" Version="1.5.2" />
    <PackageReference Include="Blazilla" Version="2.4.0" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Authentication" Version="10.0.10" />
    <PackageReference Include="MudBlazor" Version="9.7.0" />
    <PackageReference Include="MudBlazor.Translations" Version="3.4.0" />
    <PackageReference Include="PSC.Blazor.Components.Chartjs" Version="8.0.8" />
    <PackageReference Include="Refit" Version="14.0.1" />
    <PackageReference Include="Refit.HttpClientFactory" Version="14.0.1" />
    <PackageReference Include="Refit.Reflection" Version="14.0.1" />
  </ItemGroup>

</Project>
