// <auto-generated>
//     This code was generated by Refitter version 2.1.3.0.
// </auto-generated>


using Refit;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Yggdrasil.ApiClient.Contracts;

#nullable enable annotations

namespace Yggdrasil.ApiClient
{
    /// <summary>Operations for Auditoria.</summary>
    [System.CodeDom.Compiler.GeneratedCode("Refitter", "2.1.3.0")]
    public partial interface IAuditoriaApi
    {
        /// <summary>Obtiene registros de auditoría paginados y filtrados</summary>
        /// <param name="q">q parameter</param>
        /// <param name="auditEventId">auditEventId parameter</param>
        /// <param name="hasError">hasError parameter</param>
        /// <param name="fechaInicio">fechaInicio parameter</param>
        /// <param name="fechaFin">fechaFin parameter</param>
        /// <param name="page">page parameter</param>
        /// <param name="size">size parameter</param>
        /// <param name="sortColumn">sortColumn parameter</param>
        /// <param name="sortDescending">sortDescending parameter</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>401</term>
        /// <description>Unauthorized</description>
        /// </item>
        /// <item>
        /// <term>500</term>
        /// <description>Internal Server Error</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json")]
        [Get("/api/audits/audit")]
        Task<AuditListItemDtoPagedResultDtoApiResponseDto> AuditAsync([Query] string q, [Query] int? auditEventId, [Query] bool? hasError, [Query] System.DateTime? fechaInicio, [Query] System.DateTime? fechaFin, [Query] int? page, [Query] int? size, [Query] string sortColumn, [Query] bool? sortDescending);

        /// <summary>Obtiene el reporte de auditoría agrupado por usuario y evento</summary>
        /// <param name="anio">anio parameter</param>
        /// <param name="mes">mes parameter</param>
        /// <param name="userName">userName parameter</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>401</term>
        /// <description>Unauthorized</description>
        /// </item>
        /// <item>
        /// <term>500</term>
        /// <description>Internal Server Error</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json")]
        [Get("/api/audits/audit/report")]
        Task<AuditReportDtoApiResponseDto> GetAuditReportAsync([Query] int? anio, [Query] int? mes, [Query] string userName);

    }

}