// <auto-generated>
//     This code was generated by Refitter version 2.1.3.0.
// </auto-generated>


using Refit;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Yggdrasil.ApiClient.Contracts;

#nullable enable annotations

namespace Yggdrasil.ApiClient
{
    /// <summary>Operations for CatalogoSelectLists.</summary>
    [System.CodeDom.Compiler.GeneratedCode("Refitter", "2.1.3.0")]
    public partial interface ICatalogoSelectListsApi
    {
        /// <summary>Obtiene Monedas</summary>
        /// <remarks>Retorna una lista de las Monedas</remarks>
        /// <param name="searchTerm">searchTerm parameter</param>
        /// <param name="maxResults">maxResults parameter</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>400</term>
        /// <description>Bad Request</description>
        /// </item>
        /// <item>
        /// <term>401</term>
        /// <description>Unauthorized</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>Not Found</description>
        /// </item>
        /// <item>
        /// <term>500</term>
        /// <description>Internal Server Error</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json")]
        [Get("/api/cat-select-lists/monedas")]
        Task<SelectListItemDtoListApiResponseDto> GetMonedaSelectListAsync([Query] string searchTerm, [Query] int? maxResults);

        /// <summary>Obtiene Periodicidades</summary>
        /// <remarks>Retorna una lista de las Periodicidades activas</remarks>
        /// <param name="searchTerm">searchTerm parameter</param>
        /// <param name="maxResults">maxResults parameter</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>401</term>
        /// <description>Unauthorized</description>
        /// </item>
        /// <item>
        /// <term>500</term>
        /// <description>Internal Server Error</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json")]
        [Get("/api/cat-select-lists/periodicidades")]
        Task<SelectListItemDtoListApiResponseDto> GetPeriodicidadSelectListAsync([Query] string searchTerm, [Query] int? maxResults);

        /// <summary>Obtiene Tasas IVA</summary>
        /// <remarks>Retorna una lista de las Tasas IVA activas</remarks>
        /// <param name="searchTerm">searchTerm parameter</param>
        /// <param name="maxResults">maxResults parameter</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>401</term>
        /// <description>Unauthorized</description>
        /// </item>
        /// <item>
        /// <term>500</term>
        /// <description>Internal Server Error</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json")]
        [Get("/api/cat-select-lists/tasas-iva")]
        Task<SelectListItemDtoListApiResponseDto> GetTasaIvaSelectListAsync([Query] string searchTerm, [Query] int? maxResults);

        /// <summary>Obtiene Tasas Fijas</summary>
        /// <remarks>Retorna una lista de las Tasas Fijas activas</remarks>
        /// <param name="searchTerm">searchTerm parameter</param>
        /// <param name="maxResults">maxResults parameter</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>401</term>
        /// <description>Unauthorized</description>
        /// </item>
        /// <item>
        /// <term>500</term>
        /// <description>Internal Server Error</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json")]
        [Get("/api/cat-select-lists/tasas-fijas")]
        Task<SelectListItemDtoListApiResponseDto> GetTasaFijaSelectListAsync([Query] string searchTerm, [Query] int? maxResults);

        /// <summary>Obtiene Tasas Variables</summary>
        /// <remarks>Retorna una lista de las Tasas Variables</remarks>
        /// <param name="searchTerm">searchTerm parameter</param>
        /// <param name="maxResults">maxResults parameter</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>401</term>
        /// <description>Unauthorized</description>
        /// </item>
        /// <item>
        /// <term>500</term>
        /// <description>Internal Server Error</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json")]
        [Get("/api/cat-select-lists/tasas-variables")]
        Task<SelectListItemDtoListApiResponseDto> GetTasaVariableSelectListAsync([Query] string searchTerm, [Query] int? maxResults);

        /// <summary>Obtiene Bancos</summary>
        /// <remarks>Retorna una lista de los Bancos activos</remarks>
        /// <param name="searchTerm">searchTerm parameter</param>
        /// <param name="maxResults">maxResults parameter</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>401</term>
        /// <description>Unauthorized</description>
        /// </item>
        /// <item>
        /// <term>500</term>
        /// <description>Internal Server Error</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json")]
        [Get("/api/cat-select-lists/bancos")]
        Task<SelectListItemDtoListApiResponseDto> GetBancoSelectListAsync([Query] string searchTerm, [Query] int? maxResults);

    }

}