// <auto-generated>
//     This code was generated by Refitter version 2.1.3.0.
// </auto-generated>


using Refit;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Yggdrasil.ApiClient.Contracts;

#nullable enable annotations

namespace Yggdrasil.ApiClient
{
    /// <summary>Operations for CobranzaIntradias.</summary>
    [System.CodeDom.Compiler.GeneratedCode("Refitter", "2.1.3.0")]
    public partial interface ICobranzaIntradiasApi
    {
        /// <summary>Obtiene los créditos intradía paginados y ordenados</summary>
        /// <param name="page">page parameter</param>
        /// <param name="pageSize">pageSize parameter</param>
        /// <param name="sortColumn">sortColumn parameter</param>
        /// <param name="sortDesc">sortDesc parameter</param>
        /// <param name="fechaPrimeraRentaStart">fechaPrimeraRentaStart parameter</param>
        /// <param name="fechaPrimeraRentaEnd">fechaPrimeraRentaEnd parameter</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>401</term>
        /// <description>Unauthorized</description>
        /// </item>
        /// <item>
        /// <term>500</term>
        /// <description>Internal Server Error</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json")]
        [Get("/api/cob-intradias/intradias/credito")]
        Task<CreditoIntraDiaListItemDtoPagedResultDtoApiResponseDto> CobGetCreditosIntraDiaAsync([Query] int? page, [Query] int? pageSize, [Query] string sortColumn, [Query] bool? sortDesc, [Query] System.DateTime? fechaPrimeraRentaStart, [Query] System.DateTime? fechaPrimeraRentaEnd);

        /// <summary>Obtiene un crédito intradía por ID</summary>
        /// <param name="id">id parameter</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>401</term>
        /// <description>Unauthorized</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>Not Found</description>
        /// </item>
        /// <item>
        /// <term>500</term>
        /// <description>Internal Server Error</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json")]
        [Get("/api/cob-intradias/intradias/credito/{id}")]
        Task<CreditoIntradiaEditDtoApiResponseDto> CobGetCreditoIntraDiaByIdAsync(System.Guid id);

        /// <summary>Crea o actualiza un crédito intradía</summary>
        /// <param name="id">id parameter</param>
        /// <param name="body">body parameter</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>400</term>
        /// <description>Bad Request</description>
        /// </item>
        /// <item>
        /// <term>401</term>
        /// <description>Unauthorized</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>Not Found</description>
        /// </item>
        /// <item>
        /// <term>500</term>
        /// <description>Internal Server Error</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json", "Content-Type: application/json")]
        [Post("/api/cob-intradias/intradias/credito/{id}")]
        Task<GuidApiResponseDto> CobCapturarCreditoIntraDiaAsync(System.Guid id, [Body] CreditoIntradiaEditDto body);

        /// <summary>Obtiene el detalle de un crédito intradía con sus movimientos e intereses acumulados</summary>
        /// <param name="id">id parameter</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>401</term>
        /// <description>Unauthorized</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>Not Found</description>
        /// </item>
        /// <item>
        /// <term>500</term>
        /// <description>Internal Server Error</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json")]
        [Get("/api/cob-intradias/intradias/credito/{id}/detail")]
        Task<CreditoIntraDiaDetailDtoApiResponseDto> CobGetCreditoIntraDiaDetailAsync(System.Guid id);

        /// <summary>Devenga el interés acumulado de un crédito intradía a la fecha indicada</summary>
        /// <param name="creditoId">creditoId parameter</param>
        /// <param name="fechaCalculo">fechaCalculo parameter</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>401</term>
        /// <description>Unauthorized</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>Not Found</description>
        /// </item>
        /// <item>
        /// <term>500</term>
        /// <description>Internal Server Error</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json")]
        [Post("/api/cob-intradias/intradias/devengar")]
        Task<ApiResponseDto> CobDevengarCreditoIntraDiaAsync([Query] System.Guid creditoId, [Query] System.DateTime? fechaCalculo);

        /// <summary>Registra una disposición de capital sobre un crédito intradía</summary>
        /// <param name="body">body parameter</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>401</term>
        /// <description>Unauthorized</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>Not Found</description>
        /// </item>
        /// <item>
        /// <term>500</term>
        /// <description>Internal Server Error</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json", "Content-Type: application/json")]
        [Post("/api/cob-intradias/intradias/disposicion")]
        Task<ApiResponseDto> CobNewDisposicionIntraDiaAsync([Body] NewDisposicionDto body);

        /// <summary>Aplica un pago a capital sobre un crédito intradía</summary>
        /// <param name="body">body parameter</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>401</term>
        /// <description>Unauthorized</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>Not Found</description>
        /// </item>
        /// <item>
        /// <term>500</term>
        /// <description>Internal Server Error</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json", "Content-Type: application/json")]
        [Post("/api/cob-intradias/intradias/pago-capital")]
        Task<ApiResponseDto> CobPagoCapitalIntraDiaAsync([Body] PagoCapitalDto body);

        /// <summary>Aplica un prepago (interés e IVA devengados y, en su caso, capital) sobre un crédito intradía</summary>
        /// <param name="body">body parameter</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>400</term>
        /// <description>Bad Request</description>
        /// </item>
        /// <item>
        /// <term>401</term>
        /// <description>Unauthorized</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>Not Found</description>
        /// </item>
        /// <item>
        /// <term>500</term>
        /// <description>Internal Server Error</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json", "Content-Type: application/json")]
        [Post("/api/cob-intradias/intradias/prepago")]
        Task<ApiResponseDto> CobPrepagoIntraDiaAsync([Body] PrepagoDto body);

        /// <summary>Aplica un pago a intereses e IVA acumulados sobre un crédito intradía</summary>
        /// <param name="body">body parameter</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>400</term>
        /// <description>Bad Request</description>
        /// </item>
        /// <item>
        /// <term>401</term>
        /// <description>Unauthorized</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>Not Found</description>
        /// </item>
        /// <item>
        /// <term>500</term>
        /// <description>Internal Server Error</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json", "Content-Type: application/json")]
        [Post("/api/cob-intradias/intradias/pago-interes")]
        Task<ApiResponseDto> CobPagoInteresIntraDiaAsync([Body] PagoInteresDto body);

        /// <summary>Liquida el saldo total (capital, interés e IVA) de un crédito intradía</summary>
        /// <param name="body">body parameter</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>401</term>
        /// <description>Unauthorized</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>Not Found</description>
        /// </item>
        /// <item>
        /// <term>500</term>
        /// <description>Internal Server Error</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json", "Content-Type: application/json")]
        [Post("/api/cob-intradias/intradias/liquidacion")]
        Task<ApiResponseDto> CobLiquidacionIntraDiaAsync([Body] LiquidacionDto body);

        /// <summary>Elimina los movimientos y el interés acumulado registrados de un crédito intradía</summary>
        /// <param name="id">id parameter</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>401</term>
        /// <description>Unauthorized</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>Not Found</description>
        /// </item>
        /// <item>
        /// <term>500</term>
        /// <description>Internal Server Error</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json")]
        [Delete("/api/cob-intradias/intradias/credito/{id}/movimientos")]
        Task<ApiResponseDto> CobEliminarMovimientosIntraDiaAsync(System.Guid id);

        /// <summary>Calcula los valores por defecto (fecha) para una nueva disposición sobre un crédito intradía</summary>
        /// <param name="id">id parameter</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>401</term>
        /// <description>Unauthorized</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>Not Found</description>
        /// </item>
        /// <item>
        /// <term>500</term>
        /// <description>Internal Server Error</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json")]
        [Get("/api/cob-intradias/intradias/credito/{id}/nueva-disposicion")]
        Task<NewDisposicionDtoApiResponseDto> CobGetNewDisposicionIntraDiaAsync(System.Guid id);

        /// <summary>Calcula los valores por defecto (fecha) para un pago a capital sobre un crédito intradía</summary>
        /// <param name="id">id parameter</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>401</term>
        /// <description>Unauthorized</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>Not Found</description>
        /// </item>
        /// <item>
        /// <term>500</term>
        /// <description>Internal Server Error</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json")]
        [Get("/api/cob-intradias/intradias/credito/{id}/pago-capital")]
        Task<PagoCapitalDtoApiResponseDto> CobGetPagoCapitalIntraDiaAsync(System.Guid id);

        /// <summary>Calcula los valores por defecto (fecha) para un pago a intereses sobre un crédito intradía</summary>
        /// <param name="id">id parameter</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>401</term>
        /// <description>Unauthorized</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>Not Found</description>
        /// </item>
        /// <item>
        /// <term>500</term>
        /// <description>Internal Server Error</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json")]
        [Get("/api/cob-intradias/intradias/credito/{id}/pago-interes")]
        Task<PagoInteresDtoApiResponseDto> CobGetPagoInteresIntraDiaAsync(System.Guid id);

        /// <summary>Calcula los valores por defecto (fecha) para la liquidación de un crédito intradía</summary>
        /// <param name="id">id parameter</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>401</term>
        /// <description>Unauthorized</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>Not Found</description>
        /// </item>
        /// <item>
        /// <term>500</term>
        /// <description>Internal Server Error</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json")]
        [Get("/api/cob-intradias/intradias/credito/{id}/liquidacion")]
        Task<LiquidacionDtoApiResponseDto> CobGetLiquidacionIntraDiaAsync(System.Guid id);

    }

}