// <auto-generated>
//     This code was generated by Refitter version 2.1.3.0.
// </auto-generated>


using Refit;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Yggdrasil.ApiClient.Contracts;

#nullable enable annotations

namespace Yggdrasil.ApiClient
{
    /// <summary>Operations for CreditoCSConfiguracion.</summary>
    [System.CodeDom.Compiler.GeneratedCode("Refitter", "2.1.3.0")]
    public partial interface ICreditoCSConfiguracionApi
    {
        /// <summary>Obtiene un tipo de movimiento de crédito simple por ID</summary>
        /// <param name="id">id parameter</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>401</term>
        /// <description>Unauthorized</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>Not Found</description>
        /// </item>
        /// <item>
        /// <term>500</term>
        /// <description>Internal Server Error</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json")]
        [Get("/api/cs-configuracion/tipo-movimiento/{id}")]
        Task<TipoMovimientoCsEditDtoApiResponseDto> GetCSTipoMovimientoByIdAsync(int id);

        /// <summary>Actualiza un tipo de movimiento de crédito simple</summary>
        /// <param name="id">id parameter</param>
        /// <param name="body">body parameter</param>
        /// <returns>A <see cref="Task"/> that completes when the request is finished.</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>400</term>
        /// <description>Bad Request</description>
        /// </item>
        /// <item>
        /// <term>401</term>
        /// <description>Unauthorized</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>Not Found</description>
        /// </item>
        /// <item>
        /// <term>500</term>
        /// <description>Internal Server Error</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json", "Content-Type: application/json")]
        [Put("/api/cs-configuracion/tipo-movimiento/{id}")]
        Task UpdateCSTipoMovimientoAsync(int id, [Body] TipoMovimientoCsEditDto body);

        /// <summary>Elimina un tipo de movimiento de crédito simple</summary>
        /// <param name="id">id parameter</param>
        /// <returns>A <see cref="Task"/> that completes when the request is finished.</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>401</term>
        /// <description>Unauthorized</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>Not Found</description>
        /// </item>
        /// <item>
        /// <term>500</term>
        /// <description>Internal Server Error</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json")]
        [Delete("/api/cs-configuracion/tipo-movimiento/{id}")]
        Task DeleteCSTipoMovimientoAsync(int id);

        /// <summary>Obtiene tipos de movimiento de crédito simple paginados y filtrados</summary>
        /// <param name="q">q parameter</param>
        /// <param name="page">page parameter</param>
        /// <param name="size">size parameter</param>
        /// <param name="sortColumn">sortColumn parameter</param>
        /// <param name="sortDescending">sortDescending parameter</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>401</term>
        /// <description>Unauthorized</description>
        /// </item>
        /// <item>
        /// <term>500</term>
        /// <description>Internal Server Error</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json")]
        [Get("/api/cs-configuracion/tipo-movimiento")]
        Task<TipoMovimientoCsListItemDtoPagedResultDtoApiResponseDto> GetCSTipoMovimientosAsync([Query] string q, [Query] int? page, [Query] int? size, [Query] string sortColumn, [Query] bool? sortDescending);

        /// <summary>Crea un nuevo tipo de movimiento de crédito simple</summary>
        /// <param name="body">body parameter</param>
        /// <returns>Created</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>400</term>
        /// <description>Bad Request</description>
        /// </item>
        /// <item>
        /// <term>401</term>
        /// <description>Unauthorized</description>
        /// </item>
        /// <item>
        /// <term>500</term>
        /// <description>Internal Server Error</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json", "Content-Type: application/json")]
        [Post("/api/cs-configuracion/tipo-movimiento")]
        Task<Int32ApiResponseDto> CreateCSTipoMovimientoAsync([Body] TipoMovimientoCsEditDto body);

        /// <summary>Obtiene un tipo de crédito simple por ID</summary>
        /// <param name="id">id parameter</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>401</term>
        /// <description>Unauthorized</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>Not Found</description>
        /// </item>
        /// <item>
        /// <term>500</term>
        /// <description>Internal Server Error</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json")]
        [Get("/api/cs-configuracion/tipo-credito/{id}")]
        Task<TipoCreditoCsEditDtoApiResponseDto> GetCSTipoCreditoByIdAsync(int id);

        /// <summary>Actualiza un tipo de crédito simple</summary>
        /// <param name="id">id parameter</param>
        /// <param name="body">body parameter</param>
        /// <returns>A <see cref="Task"/> that completes when the request is finished.</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>400</term>
        /// <description>Bad Request</description>
        /// </item>
        /// <item>
        /// <term>401</term>
        /// <description>Unauthorized</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>Not Found</description>
        /// </item>
        /// <item>
        /// <term>500</term>
        /// <description>Internal Server Error</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json", "Content-Type: application/json")]
        [Put("/api/cs-configuracion/tipo-credito/{id}")]
        Task UpdateCSTipoCreditoAsync(int id, [Body] TipoCreditoCsEditDto body);

        /// <summary>Elimina un tipo de crédito simple</summary>
        /// <param name="id">id parameter</param>
        /// <returns>A <see cref="Task"/> that completes when the request is finished.</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>401</term>
        /// <description>Unauthorized</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>Not Found</description>
        /// </item>
        /// <item>
        /// <term>500</term>
        /// <description>Internal Server Error</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json")]
        [Delete("/api/cs-configuracion/tipo-credito/{id}")]
        Task DeleteCSTipoCreditoAsync(int id);

        /// <summary>Obtiene tipos de crédito simple paginados y filtrados</summary>
        /// <param name="q">q parameter</param>
        /// <param name="page">page parameter</param>
        /// <param name="size">size parameter</param>
        /// <param name="sortColumn">sortColumn parameter</param>
        /// <param name="sortDescending">sortDescending parameter</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>401</term>
        /// <description>Unauthorized</description>
        /// </item>
        /// <item>
        /// <term>500</term>
        /// <description>Internal Server Error</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json")]
        [Get("/api/cs-configuracion/tipo-credito")]
        Task<TipoCreditoListItemDtoPagedResultDtoApiResponseDto> GetCSTipoCreditosAsync([Query] string q, [Query] int? page, [Query] int? size, [Query] string sortColumn, [Query] bool? sortDescending);

        /// <summary>Crea un nuevo tipo de crédito simple</summary>
        /// <param name="body">body parameter</param>
        /// <returns>Created</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>400</term>
        /// <description>Bad Request</description>
        /// </item>
        /// <item>
        /// <term>401</term>
        /// <description>Unauthorized</description>
        /// </item>
        /// <item>
        /// <term>500</term>
        /// <description>Internal Server Error</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json", "Content-Type: application/json")]
        [Post("/api/cs-configuracion/tipo-credito")]
        Task<Int32ApiResponseDto> CreateCSTipoCreditoAsync([Body] TipoCreditoCsEditDto body);

        /// <summary>Sincroniza los métodos de amortización</summary>
        /// <remarks>Sincroniza el catálogo de métodos de amortización con las estrategias registradas en el sistema (DI), agregando, actualizando y desactivando según corresponda</remarks>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>401</term>
        /// <description>Unauthorized</description>
        /// </item>
        /// <item>
        /// <term>500</term>
        /// <description>Internal Server Error</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json")]
        [Post("/api/cs-configuracion/metodo-armortizacion/sync")]
        Task<ApiResponseDto> SyncCSMetodoArmotizacionAsync();

    }

}