// <auto-generated>
//     This code was generated by Refitter version 2.1.3.0.
// </auto-generated>


using Refit;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Yggdrasil.ApiClient.Contracts;

#nullable enable annotations

namespace Yggdrasil.ApiClient
{
    /// <summary>Operations for CreditoCSCreditos.</summary>
    [System.CodeDom.Compiler.GeneratedCode("Refitter", "2.1.3.0")]
    public partial interface ICreditoCSCreditosApi
    {
        /// <summary>Obtiene créditos simples filtrados y paginados</summary>
        /// <param name="q">q parameter</param>
        /// <param name="page">page parameter</param>
        /// <param name="pageSize">pageSize parameter</param>
        /// <param name="sortColumn">sortColumn parameter</param>
        /// <param name="sortDesc">sortDesc parameter</param>
        /// <param name="tipoCreditoId">tipoCreditoId parameter</param>
        /// <param name="estatusCreditoId">estatusCreditoId parameter</param>
        /// <param name="fechaActivacionStart">fechaActivacionStart parameter</param>
        /// <param name="fechaActivacionEnd">fechaActivacionEnd parameter</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>401</term>
        /// <description>Unauthorized</description>
        /// </item>
        /// <item>
        /// <term>500</term>
        /// <description>Internal Server Error</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json")]
        [Get("/api/cs-creditos/credito")]
        Task<CreditoCsListItemDtoPagedResultDtoApiResponseDto> GetCSCreditosAsync([Query] string q, [Query] int? page, [Query] int? pageSize, [Query] string sortColumn, [Query] bool? sortDesc, [Query] int? tipoCreditoId, [Query] int? estatusCreditoId, [Query] System.DateTime? fechaActivacionStart, [Query] System.DateTime? fechaActivacionEnd);

        /// <summary>Obtiene el detalle completo de un crédito simple</summary>
        /// <param name="id">id parameter</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>401</term>
        /// <description>Unauthorized</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>Not Found</description>
        /// </item>
        /// <item>
        /// <term>500</term>
        /// <description>Internal Server Error</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json")]
        [Get("/api/cs-creditos/credito/{id}/detail")]
        Task<CreditoCsDetailDtoApiResponseDto> GetCSCreditoDetailAsync(int id);

        /// <summary>Obtiene la tabla de amortización de un crédito simple</summary>
        /// <param name="id">id parameter</param>
        /// <param name="version">version parameter</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>401</term>
        /// <description>Unauthorized</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>Not Found</description>
        /// </item>
        /// <item>
        /// <term>500</term>
        /// <description>Internal Server Error</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json")]
        [Get("/api/cs-creditos/credito/{id}/tabla-amortiza")]
        Task<TablaAmortizaCsItemDtoListApiResponseDto> GetCSTablaAmortizaAsync(int id, [Query] int? version);

    }

}