// <auto-generated>
//     This code was generated by Refitter version 2.1.3.0.
// </auto-generated>


using Refit;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Yggdrasil.ApiClient.Contracts;

#nullable enable annotations

namespace Yggdrasil.ApiClient
{
    /// <summary>Operations for CreditoSelectLists.</summary>
    [System.CodeDom.Compiler.GeneratedCode("Refitter", "2.1.3.0")]
    public partial interface ICreditoSelectListsApi
    {
        /// <summary>Obtiene Tipos de Domicilio</summary>
        /// <remarks>Retorna una lista de Tipos de Domicilio</remarks>
        /// <param name="searchTerm">searchTerm parameter</param>
        /// <param name="maxResults">maxResults parameter</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>400</term>
        /// <description>Bad Request</description>
        /// </item>
        /// <item>
        /// <term>401</term>
        /// <description>Unauthorized</description>
        /// </item>
        /// <item>
        /// <term>500</term>
        /// <description>Internal Server Error</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json")]
        [Get("/api/fi-select-lists/tipos-domicilio")]
        Task<SelectListItemDtoListApiResponseDto> GetTipoDomicilioSelectListAsync([Query] string searchTerm, [Query] int? maxResults);

        /// <summary>Obtiene Tipos de Persona</summary>
        /// <remarks>Retorna una lista de Tipos de Persona</remarks>
        /// <param name="searchTerm">searchTerm parameter</param>
        /// <param name="maxResults">maxResults parameter</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>400</term>
        /// <description>Bad Request</description>
        /// </item>
        /// <item>
        /// <term>401</term>
        /// <description>Unauthorized</description>
        /// </item>
        /// <item>
        /// <term>500</term>
        /// <description>Internal Server Error</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json")]
        [Get("/api/fi-select-lists/tipos-persona")]
        Task<SelectListItemDtoListApiResponseDto> GetTipoPersonaSelectListAsync([Query] string searchTerm, [Query] int? maxResults);

        /// <summary>Obtiene Estados Civiles</summary>
        /// <remarks>Retorna una lista de Estados Civiles</remarks>
        /// <param name="searchTerm">searchTerm parameter</param>
        /// <param name="maxResults">maxResults parameter</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>400</term>
        /// <description>Bad Request</description>
        /// </item>
        /// <item>
        /// <term>401</term>
        /// <description>Unauthorized</description>
        /// </item>
        /// <item>
        /// <term>500</term>
        /// <description>Internal Server Error</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json")]
        [Get("/api/fi-select-lists/estados-civiles")]
        Task<SelectListItemDtoListApiResponseDto> GetEdoCivilSelectListAsync([Query] string searchTerm, [Query] int? maxResults);

        /// <summary>Obtiene Géneros</summary>
        /// <remarks>Retorna una lista de Géneros</remarks>
        /// <param name="searchTerm">searchTerm parameter</param>
        /// <param name="maxResults">maxResults parameter</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>400</term>
        /// <description>Bad Request</description>
        /// </item>
        /// <item>
        /// <term>401</term>
        /// <description>Unauthorized</description>
        /// </item>
        /// <item>
        /// <term>500</term>
        /// <description>Internal Server Error</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json")]
        [Get("/api/fi-select-lists/generos")]
        Task<SelectListItemDtoListApiResponseDto> GetGeneroSelectListAsync([Query] string searchTerm, [Query] int? maxResults);

        /// <summary>Obtiene Empresas</summary>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>401</term>
        /// <description>Unauthorized</description>
        /// </item>
        /// <item>
        /// <term>500</term>
        /// <description>Internal Server Error</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json")]
        [Get("/api/fi-select-lists/empresas")]
        Task<SelectListItemDtoListApiResponseDto> GetEmpresaSelectListAsync();

        /// <summary>Obtiene Tipos de Movimiento activos</summary>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>401</term>
        /// <description>Unauthorized</description>
        /// </item>
        /// <item>
        /// <term>500</term>
        /// <description>Internal Server Error</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json")]
        [Get("/api/fi-select-lists/tipos-movimiento")]
        Task<SelectListItemDtoListApiResponseDto> GetTipoMovimientoSelectListAsync();

        /// <summary>Obtiene Tipos de Pago</summary>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>401</term>
        /// <description>Unauthorized</description>
        /// </item>
        /// <item>
        /// <term>500</term>
        /// <description>Internal Server Error</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json")]
        [Get("/api/fi-select-lists/tipos-pago")]
        Task<SelectListItemDtoListApiResponseDto> GetTipoPagoSelectListAsync();

        /// <summary>Obtiene Formas de Pago</summary>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>401</term>
        /// <description>Unauthorized</description>
        /// </item>
        /// <item>
        /// <term>500</term>
        /// <description>Internal Server Error</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json")]
        [Get("/api/fi-select-lists/formas-pago")]
        Task<SelectListItemDtoListApiResponseDto> GetFormaPagoSelectListAsync();

        /// <summary>Obtiene Tipos de Calculo</summary>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>401</term>
        /// <description>Unauthorized</description>
        /// </item>
        /// <item>
        /// <term>500</term>
        /// <description>Internal Server Error</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json")]
        [Get("/api/fi-select-lists/tipos-calculo")]
        Task<SelectListItemDtoListApiResponseDto> GetTipoCalculoSelectListAsync();

    }

}