// <auto-generated>
//     This code was generated by Refitter version 2.1.3.0.
// </auto-generated>


using Refit;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Yggdrasil.ApiClient.Contracts;

#nullable enable annotations

namespace Yggdrasil.ApiClient
{
    /// <summary>Operations for CreditoCreditos.</summary>
    [System.CodeDom.Compiler.GeneratedCode("Refitter", "2.1.3.0")]
    public partial interface ICreditoCreditosApi
    {
        /// <summary>Obtiene créditos filtrados y paginados</summary>
        /// <param name="q">q parameter</param>
        /// <param name="page">page parameter</param>
        /// <param name="pageSize">pageSize parameter</param>
        /// <param name="sortColumn">sortColumn parameter</param>
        /// <param name="sortDesc">sortDesc parameter</param>
        /// <param name="productoId">productoId parameter</param>
        /// <param name="estatusCreditoId">estatusCreditoId parameter</param>
        /// <param name="fechaActivacionStart">fechaActivacionStart parameter</param>
        /// <param name="fechaActivacionEnd">fechaActivacionEnd parameter</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>401</term>
        /// <description>Unauthorized</description>
        /// </item>
        /// <item>
        /// <term>500</term>
        /// <description>Internal Server Error</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json")]
        [Get("/api/fi-creditos/credito")]
        Task<CreditoListItemDtoPagedResultDtoApiResponseDto> GetCreditosAsync([Query] string q, [Query] int? page, [Query] int? pageSize, [Query] string sortColumn, [Query] bool? sortDesc, [Query] int? productoId, [Query] int? estatusCreditoId, [Query] System.DateTime? fechaActivacionStart, [Query] System.DateTime? fechaActivacionEnd);

        /// <summary>Obtiene el detalle completo de un crédito (crédito, cliente y producto)</summary>
        /// <param name="id">id parameter</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>401</term>
        /// <description>Unauthorized</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>Not Found</description>
        /// </item>
        /// <item>
        /// <term>500</term>
        /// <description>Internal Server Error</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json")]
        [Get("/api/fi-creditos/credito/{id}/detail")]
        Task<CreditoDetailDtoApiResponseDto> GetCreditoDetailAsync(int id);

        /// <summary>Obtiene la tabla de amortización de un crédito</summary>
        /// <param name="id">id parameter</param>
        /// <param name="version">version parameter</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>401</term>
        /// <description>Unauthorized</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>Not Found</description>
        /// </item>
        /// <item>
        /// <term>500</term>
        /// <description>Internal Server Error</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json")]
        [Get("/api/fi-creditos/credito/{id}/tabla-amortiza")]
        Task<TablaAmortizaItemDtoListApiResponseDto> GetTablaAmortizaAsync(int id, [Query] int? version);

        /// <summary>Obtiene los movimientos de un crédito</summary>
        /// <param name="id">id parameter</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>401</term>
        /// <description>Unauthorized</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>Not Found</description>
        /// </item>
        /// <item>
        /// <term>500</term>
        /// <description>Internal Server Error</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json")]
        [Get("/api/fi-creditos/credito/{id}/movimientos")]
        Task<MovimientoItemDtoListApiResponseDto> GetMovimientosAsync(int id);

        /// <summary>Obtiene los pagos de un crédito (creditoId) o de todos los créditos de una persona (personaId)</summary>
        /// <param name="personaId">personaId parameter</param>
        /// <param name="creditoId">creditoId parameter</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>400</term>
        /// <description>Bad Request</description>
        /// </item>
        /// <item>
        /// <term>401</term>
        /// <description>Unauthorized</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>Not Found</description>
        /// </item>
        /// <item>
        /// <term>500</term>
        /// <description>Internal Server Error</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json")]
        [Get("/api/fi-creditos/credito/pagos")]
        Task<PagoItemDtoListApiResponseDto> GetPagosAsync([Query] int? personaId, [Query] int? creditoId);

        /// <summary>Obtiene el detalle de un pago</summary>
        /// <param name="pagoId">pagoId parameter</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>401</term>
        /// <description>Unauthorized</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>Not Found</description>
        /// </item>
        /// <item>
        /// <term>500</term>
        /// <description>Internal Server Error</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json")]
        [Get("/api/fi-creditos/credito/pagos/{pagoId}/detail")]
        Task<PagoDetailDtoApiResponseDto> GetPagoDetailByIdAsync(int pagoId);

    }

}