// <auto-generated>
//     This code was generated by Refitter version 2.1.3.0.
// </auto-generated>


using Refit;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Yggdrasil.ApiClient.Contracts;

#nullable enable annotations

namespace Yggdrasil.ApiClient
{
    /// <summary>Operations for CreditoCSCatalogos.</summary>
    [System.CodeDom.Compiler.GeneratedCode("Refitter", "2.1.3.0")]
    public partial interface ICreditoCSCatalogosApi
    {
        /// <summary>Obtiene un tipo de pago de crédito simple por ID</summary>
        /// <param name="id">id parameter</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>401</term>
        /// <description>Unauthorized</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>Not Found</description>
        /// </item>
        /// <item>
        /// <term>500</term>
        /// <description>Internal Server Error</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json")]
        [Get("/api/cs-catalogos/tipo-pago/{id}")]
        Task<TipoPagoCsEditDtoApiResponseDto> GetCSTipoPagoByIdAsync(int id);

        /// <summary>Actualiza un tipo de pago de crédito simple</summary>
        /// <param name="id">id parameter</param>
        /// <param name="body">body parameter</param>
        /// <returns>A <see cref="Task"/> that completes when the request is finished.</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>400</term>
        /// <description>Bad Request</description>
        /// </item>
        /// <item>
        /// <term>401</term>
        /// <description>Unauthorized</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>Not Found</description>
        /// </item>
        /// <item>
        /// <term>500</term>
        /// <description>Internal Server Error</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json", "Content-Type: application/json")]
        [Put("/api/cs-catalogos/tipo-pago/{id}")]
        Task UpdateCSTipoPagoAsync(int id, [Body] TipoPagoCsEditDto body);

        /// <summary>Elimina un tipo de pago de crédito simple</summary>
        /// <param name="id">id parameter</param>
        /// <returns>A <see cref="Task"/> that completes when the request is finished.</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>401</term>
        /// <description>Unauthorized</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>Not Found</description>
        /// </item>
        /// <item>
        /// <term>500</term>
        /// <description>Internal Server Error</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json")]
        [Delete("/api/cs-catalogos/tipo-pago/{id}")]
        Task DeleteCSTipoPagoAsync(int id);

        /// <summary>Obtiene tipos de pago de crédito simple paginados y filtrados</summary>
        /// <param name="q">q parameter</param>
        /// <param name="page">page parameter</param>
        /// <param name="size">size parameter</param>
        /// <param name="sortColumn">sortColumn parameter</param>
        /// <param name="sortDescending">sortDescending parameter</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>401</term>
        /// <description>Unauthorized</description>
        /// </item>
        /// <item>
        /// <term>500</term>
        /// <description>Internal Server Error</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json")]
        [Get("/api/cs-catalogos/tipo-pago")]
        Task<TipoPagoCsListItemDtoPagedResultDtoApiResponseDto> GetCSTipoPagosAsync([Query] string q, [Query] int? page, [Query] int? size, [Query] string sortColumn, [Query] bool? sortDescending);

        /// <summary>Crea un nuevo tipo de pago de crédito simple</summary>
        /// <param name="body">body parameter</param>
        /// <returns>Created</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>400</term>
        /// <description>Bad Request</description>
        /// </item>
        /// <item>
        /// <term>401</term>
        /// <description>Unauthorized</description>
        /// </item>
        /// <item>
        /// <term>500</term>
        /// <description>Internal Server Error</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json", "Content-Type: application/json")]
        [Post("/api/cs-catalogos/tipo-pago")]
        Task<Int32ApiResponseDto> CreateCSTipoPagoAsync([Body] TipoPagoCsEditDto body);

    }

}