// <auto-generated>
//     This code was generated by Refitter version 2.1.3.0.
// </auto-generated>


using Refit;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Yggdrasil.ApiClient.Contracts;

#nullable enable annotations

namespace Yggdrasil.ApiClient
{
    /// <summary>Operations for CreditoCSSelectLists.</summary>
    [System.CodeDom.Compiler.GeneratedCode("Refitter", "2.1.3.0")]
    public partial interface ICreditoCSSelectListsApi
    {
        /// <summary>Obtiene Tipos de Crédito</summary>
        /// <remarks>Retorna una lista de Tipos de Crédito de crédito simple</remarks>
        /// <param name="searchTerm">searchTerm parameter</param>
        /// <param name="maxResults">maxResults parameter</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>401</term>
        /// <description>Unauthorized</description>
        /// </item>
        /// <item>
        /// <term>500</term>
        /// <description>Internal Server Error</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json")]
        [Get("/api/cs-select-lists/tipos-credito")]
        Task<SelectListItemDtoListApiResponseDto> GetCSTipoCreditoSelectListAsync([Query] string searchTerm, [Query] int? maxResults);

        /// <summary>Obtiene Métodos de Amortización</summary>
        /// <remarks>Retorna una lista de Métodos de Amortización activos</remarks>
        /// <param name="searchTerm">searchTerm parameter</param>
        /// <param name="maxResults">maxResults parameter</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>401</term>
        /// <description>Unauthorized</description>
        /// </item>
        /// <item>
        /// <term>500</term>
        /// <description>Internal Server Error</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json")]
        [Get("/api/cs-select-lists/metodos-armotizacion")]
        Task<SelectListItemDtoListApiResponseDto> GetCSMetodoArmotizacionSelectListAsync([Query] string searchTerm, [Query] int? maxResults);

        /// <summary>Obtiene Tipos de Movimiento</summary>
        /// <remarks>Retorna una lista de Tipos de Movimiento de crédito simple activos</remarks>
        /// <param name="searchTerm">searchTerm parameter</param>
        /// <param name="maxResults">maxResults parameter</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>401</term>
        /// <description>Unauthorized</description>
        /// </item>
        /// <item>
        /// <term>500</term>
        /// <description>Internal Server Error</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json")]
        [Get("/api/cs-select-lists/tipos-movimiento")]
        Task<SelectListItemDtoListApiResponseDto> GetCSTipoMovimientoSelectListAsync([Query] string searchTerm, [Query] int? maxResults);

    }

}