// <auto-generated>
//     This code was generated by Refitter version 2.1.3.0.
// </auto-generated>


using Refit;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Yggdrasil.ApiClient.Contracts;

#nullable enable annotations

namespace Yggdrasil.ApiClient
{
    /// <summary>Operations for Reportes.</summary>
    [System.CodeDom.Compiler.GeneratedCode("Refitter", "2.1.3.0")]
    public partial interface IReportesApi
    {
        /// <summary>Obtiene un reporte por ID</summary>
        /// <param name="id">id parameter</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>404</term>
        /// <description>Not Found</description>
        /// </item>
        /// <item>
        /// <term>500</term>
        /// <description>Internal Server Error</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json")]
        [Get("/api/reportes/reporte/{id}")]
        Task<ReporteEditDtoApiResponseDto> GetReporteByIdAsync(int id);

        /// <summary>Actualiza un reporte</summary>
        /// <param name="id">id parameter</param>
        /// <param name="body">body parameter</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>400</term>
        /// <description>Bad Request</description>
        /// </item>
        /// <item>
        /// <term>404</term>
        /// <description>Not Found</description>
        /// </item>
        /// <item>
        /// <term>500</term>
        /// <description>Internal Server Error</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json", "Content-Type: application/json")]
        [Put("/api/reportes/reporte/{id}")]
        Task<ApiResponseDto> UpdateReporteAsync(int id, [Body] ReporteEditDto body);

        /// <summary>Elimina un reporte y sus parámetros</summary>
        /// <param name="id">id parameter</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>404</term>
        /// <description>Not Found</description>
        /// </item>
        /// <item>
        /// <term>500</term>
        /// <description>Internal Server Error</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json")]
        [Delete("/api/reportes/reporte/{id}")]
        Task<ApiResponseDto> DeleteReporteAsync(int id);

        /// <summary>Obtiene reportes paginados y filtrados</summary>
        /// <param name="q">q parameter</param>
        /// <param name="page">page parameter</param>
        /// <param name="size">size parameter</param>
        /// <param name="sortColumn">sortColumn parameter</param>
        /// <param name="sortDescending">sortDescending parameter</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>500</term>
        /// <description>Internal Server Error</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json")]
        [Get("/api/reportes/reporte")]
        Task<ReporteListItemDtoPagedResultDtoApiResponseDto> GetReportesAsync([Query] string q, [Query] int? page, [Query] int? size, [Query] string sortColumn, [Query] bool? sortDescending);

        /// <summary>Crea un nuevo reporte</summary>
        /// <param name="body">body parameter</param>
        /// <returns>Created</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>400</term>
        /// <description>Bad Request</description>
        /// </item>
        /// <item>
        /// <term>500</term>
        /// <description>Internal Server Error</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json", "Content-Type: application/json")]
        [Post("/api/reportes/reporte")]
        Task<Int32ApiResponseDto> CreateReporteAsync([Body] ReporteEditDto body);

        /// <summary>Busca reportes para lista de selección</summary>
        /// <param name="q">q parameter</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>500</term>
        /// <description>Internal Server Error</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json")]
        [Get("/api/reportes/reporte/search")]
        Task<SelectReporteDtoListApiResponseDto> SearchReportesAsync([Query] string q);

        /// <summary>Obtiene la configuración de parámetros de un reporte para su ejecución</summary>
        /// <param name="id">id parameter</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>404</term>
        /// <description>Not Found</description>
        /// </item>
        /// <item>
        /// <term>500</term>
        /// <description>Internal Server Error</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json")]
        [Get("/api/reportes/reporte/{id}/configuracion")]
        Task<ReporteExecuteDtoApiResponseDto> GetReporteConfiguracionAsync(int id);

        /// <summary>Ejecuta un reporte y retorna el archivo generado (Excel o Texto)</summary>
        /// <param name="guardarArchivo">guardarArchivo parameter</param>
        /// <param name="body">body parameter</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>404</term>
        /// <description>Not Found</description>
        /// </item>
        /// <item>
        /// <term>500</term>
        /// <description>Internal Server Error</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json", "Content-Type: application/json")]
        [Post("/api/reportes/reporte/ejecutar")]
        Task<ReporteExportDtoApiResponseDto> EjecutarReporteAsync([Query] bool? guardarArchivo, [Body] ReporteExecuteDto body);

        /// <summary>Registra una automatización de reporte</summary>
        /// <param name="body">body parameter</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>500</term>
        /// <description>Internal Server Error</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json", "Content-Type: application/json")]
        [Post("/api/reportes/reporte/automatizar")]
        Task<ApiResponseDto> AutomatizarReporteAsync([Body] ReporteExecuteDto body);

        /// <summary>Obtiene archivos generados paginados, filtrable por reporte</summary>
        /// <param name="reporteId">reporteId parameter</param>
        /// <param name="page">page parameter</param>
        /// <param name="size">size parameter</param>
        /// <param name="sortColumn">sortColumn parameter</param>
        /// <param name="sortDescending">sortDescending parameter</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>500</term>
        /// <description>Internal Server Error</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json")]
        [Get("/api/reportes/archivo")]
        Task<ArchivoListItemDtoPagedResultDtoApiResponseDto> GetArchivosAsync([Query] int? reporteId, [Query] int? page, [Query] int? size, [Query] string sortColumn, [Query] bool? sortDescending);

        /// <summary>Descarga un archivo generado por ID</summary>
        /// <param name="id">id parameter</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>404</term>
        /// <description>Not Found</description>
        /// </item>
        /// <item>
        /// <term>500</term>
        /// <description>Internal Server Error</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json")]
        [Get("/api/reportes/archivo/{id}/download")]
        Task<ReporteExportDtoApiResponseDto> DownloadArchivoAsync(System.Guid id);

        /// <summary>Elimina un archivo del disco y su registro</summary>
        /// <param name="id">id parameter</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>404</term>
        /// <description>Not Found</description>
        /// </item>
        /// <item>
        /// <term>500</term>
        /// <description>Internal Server Error</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json")]
        [Delete("/api/reportes/archivo/{id}")]
        Task<ApiResponseDto> DeleteArchivoAsync(System.Guid id);

        /// <summary>Obtiene un parámetro por ID</summary>
        /// <param name="id">id parameter</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>404</term>
        /// <description>Not Found</description>
        /// </item>
        /// <item>
        /// <term>500</term>
        /// <description>Internal Server Error</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json")]
        [Get("/api/reportes/parametro/{id}")]
        Task<ParametroEditDtoApiResponseDto> GetParametroByIdAsync(System.Guid id);

        /// <summary>Actualiza la configuración de un parámetro</summary>
        /// <param name="id">id parameter</param>
        /// <param name="body">body parameter</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>404</term>
        /// <description>Not Found</description>
        /// </item>
        /// <item>
        /// <term>500</term>
        /// <description>Internal Server Error</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json", "Content-Type: application/json")]
        [Put("/api/reportes/parametro/{id}")]
        Task<ApiResponseDto> UpdateParametroAsync(System.Guid id, [Body] ParametroEditDto body);

        /// <summary>Obtiene parámetros filtrados por reporte</summary>
        /// <param name="reporteId">reporteId parameter</param>
        /// <param name="q">q parameter</param>
        /// <returns>OK</returns>
        /// <exception cref="ApiException">
        /// Thrown when the request returns a non-success status code:
        /// <list type="table">
        /// <listheader>
        /// <term>Status</term>
        /// <description>Description</description>
        /// </listheader>
        /// <item>
        /// <term>500</term>
        /// <description>Internal Server Error</description>
        /// </item>
        /// </list>
        /// </exception>
        [Headers("Accept: application/json")]
        [Get("/api/reportes/parametro")]
        Task<ParametroListItemDtoListApiResponseDto> GetParametrosAsync([Query] int? reporteId, [Query] string q);

    }

}