<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Yggdrasil.Common\Yggdrasil.Common.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Features\Catalogos\Commands\" />
    <Folder Include="Features\Catalogos\DTOs\" />
    <Folder Include="Features\Catalogos\Queries\" />
    <Folder Include="Features\Catalogos\Specifications\" />
    <Folder Include="Features\Operaciones\Liquidacion\" />
    <Folder Include="Features\Operaciones\CancelarCredito\" />
  </ItemGroup>
</Project>
